version: '3'
services:
  frontend:
    # image: name of the image stored inside the external artifacts provider
    build:
      context: ./client
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    # command: production command here

  backend:
    # image: name of the image stored inside the external artifacts provider
    build:
      context: ./server
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    # command: production command here
